const NPStorage={
  KEYS:{USERS:'np_users',CURRENT:'np_current',STUDENTS:'np_students',PROGRESS:'np_progress',ACHIEVEMENTS:'np_achievements',ACCESS:'np_access',LOG:'np_log',STORIES:'np_stories'},
  get(k,f){try{const d=localStorage.getItem(k);return d?JSON.parse(d):(f!==undefined?f:null)}catch(e){return f!==undefined?f:null}},
  set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}},
  remove(k){try{localStorage.removeItem(k);return true}catch(e){return false}},
  getUsers(){return this.get(this.KEYS.USERS,[])},
  setUsers(u){return this.set(this.KEYS.USERS,u)},
  addUser(u){const users=this.getUsers();u.id=u.id||'u_'+Date.now()+'_'+Math.random().toString(36).substr(2,9);u.createdAt=u.createdAt||Date.now();users.push(u);return this.setUsers(users)},
  updateUser(id,p){const users=this.getUsers();const i=users.findIndex(u=>u.id===id);if(i!==-1){users[i]={...users[i],...p};return this.setUsers(users)}return false},
  getUser(id){return this.getUsers().find(u=>u.id===id)},
  getUserByEmail(e){return this.getUsers().find(u=>u.email===e)},
  getCurrent(){return this.get(this.KEYS.CURRENT)},
  setCurrent(u){return this.set(this.KEYS.CURRENT,u)},
  clearCurrent(){return this.remove(this.KEYS.CURRENT)},
  getStudents(){return this.get(this.KEYS.STUDENTS,[])},
  setStudents(s){return this.set(this.KEYS.STUDENTS,s)},
  addStudent(s){const list=this.getStudents();s.id=s.id||'s_'+Date.now();list.push(s);return this.setStudents(list)},
  getStudent(id){return this.getStudents().find(s=>s.id===id)},
  updateStudent(id,p){return this.setStudents(this.getStudents().map(s=>s.id===id?{...s,...p}:s))},
  getProgress(sid){const a=this.get(this.KEYS.PROGRESS,{});return a[sid]||[]},
  addProgress(sid,e){const a=this.get(this.KEYS.PROGRESS,{});a[sid]=a[sid]||[];e.id='p_'+Date.now();e.date=Date.now();a[sid].push(e);return this.set(this.KEYS.PROGRESS,a)},
  getAchievements(sid){const a=this.get(this.KEYS.ACHIEVEMENTS,{});return a[sid]||[]},
  addAchievement(sid,ac){const a=this.get(this.KEYS.ACHIEVEMENTS,{});a[sid]=a[sid]||[];if(!a[sid].find(x=>x.id===ac.id)){a[sid].push(ac);return this.set(this.KEYS.ACHIEVEMENTS,a)}return false},
  getAccess(){return this.get(this.KEYS.ACCESS,{highContrast:false,largeButtons:false,largeFont:false,reduceMotion:false,sound:true,speech:false})},
  setAccess(s){return this.set(this.KEYS.ACCESS,s)},
  addLog(action,uid,details){const logs=this.get(this.KEYS.LOG,[]);logs.push({id:'l_'+Date.now(),action,userId:uid,details,date:Date.now()});return this.set(this.KEYS.LOG,logs)},
  getLogs(){return this.get(this.KEYS.LOG,[])},
  getStoriesRead(){return this.get(this.KEYS.STORIES,[])},
  markStoryRead(id){const list=this.getStoriesRead();if(!list.includes(id)){list.push(id);return this.set(this.KEYS.STORIES,list)}return false}
};
window.NPStorage=NPStorage;