const NPStorage=(()=>{const KEYS={PROFILE:'np_profile',STUDENTS:'np_students',TEACHERS:'np_teachers',CLASSES:'np_classes',PROGRESS:'np_progress',ACHIEVEMENTS:'np_achievements',SETTINGS:'np_settings',ACCESSIBILITY:'np_accessibility',CURRENT_USER:'np_current_user'};
const get=(k,f=null)=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}};
const set=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const remove=(k)=>{try{localStorage.removeItem(k)}catch(e){}};
const getProfile=()=>get(KEYS.PROFILE);const setProfile=(p)=>set(KEYS.PROFILE,p);
const getStudents=()=>get(KEYS.STUDENTS,[]);const setStudents=(l)=>set(KEYS.STUDENTS,l);
const addStudent=(s)=>{const l=getStudents();s.id=s.id||'st_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);s.createdAt=s.createdAt||Date.now();l.push(s);setStudents(l);return s};
const updateStudent=(id,p)=>setStudents(getStudents().map(s=>s.id===id?{...s,...p}:s));
const removeStudent=(id)=>setStudents(getStudents().filter(s=>s.id!==id));
const getStudent=(id)=>getStudents().find(s=>s.id===id);
const getTeachers=()=>get(KEYS.TEACHERS,[]);const addTeacher=(t)=>{const l=getTeachers();t.id=t.id||'tc_'+Date.now();l.push(t);set(KEYS.TEACHERS,l);return t};
const setTeachers=(l)=>set(KEYS.TEACHERS,l);
const getClasses=()=>get(KEYS.CLASSES,[]);const addClass=(c)=>{const l=getClasses();c.id=c.id||'cl_'+Date.now();l.push(c);set(KEYS.CLASSES,l);return c};const setClasses=(l)=>set(KEYS.CLASSES,l);
const getProgress=(sid)=>{const a=get(KEYS.PROGRESS,{});return a[sid]||[]};
const addProgress=(sid,e)=>{const a=get(KEYS.PROGRESS,{});a[sid]=a[sid]||[];e.id=e.id||'pr_'+Date.now();e.date=e.date||Date.now();a[sid].push(e);set(KEYS.PROGRESS,a)};
const getAchievements=(sid)=>{const a=get(KEYS.ACHIEVEMENTS,{});return a[sid]||[]};
const addAchievement=(sid,ac)=>{const a=get(KEYS.ACHIEVEMENTS,{});a[sid]=a[sid]||[];if(!a[sid].find(x=>x.id===ac.id)){a[sid].push(ac);set(KEYS.ACHIEVEMENTS,a);return true}return false};
const getAccessibility=()=>get(KEYS.ACCESSIBILITY,{fontSize:16,highContrast:false,reduceMotion:false,sound:true,speech:false,largeButtons:false});
const setAccessibility=(a)=>set(KEYS.ACCESSIBILITY,a);
return{KEYS,get,set,remove,getProfile,setProfile,getStudents,setStudents,addStudent,updateStudent,removeStudent,getStudent,getTeachers,setTeachers,addTeacher,getClasses,setClasses,addClass,getProgress,addProgress,getAchievements,addAchievement,getAccessibility,setAccessibility}})();
window.NPStorage=NPStorage;